### ISSUE TITLE
Windows 10 ModuleNotFoundError: No module named 'virtualenv' Exiting due to failure

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [aws/aws-elastic-beanstalk-cli-setup#112]
==============================================
II. Creating self-contained EBCLI installation
==============================================
Installing the EBCLI in C:\Users\me\.ebcli-virtual-env

******************************************
1. Creating exclusive virtualenv for EBCLI
******************************************
Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\me\aws-elastic-beanstalk-cli-setup\scripts\virtualenv\bin\virtualenv.exe\__main__.py", line 5, in <module>
ModuleNotFoundError: No module named 'virtualenv'
Exiting due to failure
PS C:\Users\me>

**Comment by MaxmaxmaximusAWS** [comment]
temp solution:

`pip install virtualenv`

**Comment by xeladsn** [comment]
This comment has been the solution for me : https://github.com/aws/aws-elastic-beanstalk-cli-setup/issues/19#issuecomment-497930712.

Seemed that powershell or windows prompt had to be run as admin to add virtualenv to PATH.
