### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/mbrant/.ebcli-virtual-env/bin/activate_this.py'

### ISSUE THREAD

**Issue by michaelbrant** [aws/aws-elastic-beanstalk-cli-setup#134]
**1. Please specify the following:**
 - OS: [e.g. OS X, Ubuntu, Windows, etc.]: Ubuntu 22.04
 - Shell (Bash, PowerShell, Zsh, etc.): Bash

- [ X ] **I have reviewed the troubleshooting tips described [here]() and they do not solve my problem**

**2. Description**

Here's the stacktrace:

***********************************
1. Locating virtualenv installation
***********************************

******************************************
2. Creating exclusive virtualenv for EBCLI
******************************************
created virtual environment CPython3.10.4.final.0-64 in 757ms
  creator CPython3Posix(dest=/home/mbrant/.ebcli-virtual-env, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/mbrant/.local/share/virtualenv)
    added seed packages: pip==22.1.2, setuptools==62.2.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

************************
3. Activating virtualenv
************************
Traceback (most recent call last):
  File "/home/mbrant/repos/./aws-elastic-beanstalk-cli-setup/scripts/ebcli_installer.py", line 870, in <module>
    _activate_virtualenv(virtualenv_location)
  File "/home/mbrant/repos/./aws-elastic-beanstalk-cli-setup/scripts/ebcli_installer.py", line 228, in wrapped
    return_value = func(*args)
  File "/home/mbrant/repos/./aws-elastic-beanstalk-cli-setup/scripts/ebcli_installer.py", line 260, in _activate_virtualenv
    exec(open(activate_this_path).read(), dict(__file__=activate_this_path))
FileNotFoundError: [Errno 2] No such file or directory: '/home/mbrant/.ebcli-virtual-env/bin/activate_this.py'

**Comment by michaelbrant** [comment]
I was able to get this working by using python 3.9. I was using python 3.10 when I experienced the failure.
