### ISSUE TITLE
Recommend pipx for a simple install process

### ISSUE THREAD

**Issue by yolabingo** [aws/aws-elastic-beanstalk-cli-setup#149]
**1. Please specify the following:**
 - OS: OS X, linux, windows
 - Shell: Most any
 
- [x ] **I have reviewed the troubleshooting tips described [here]() and they do not solve my problem**

**2. Description**
Add **pipx** as an install method in the README.

**Install instructions:**
1. Install [pipx](https://pypa.github.io/pipx/)
2. `pipx install awsebcli` 

Using pipx is much simpler than manually managing python vitualenvs. Pipx is an established, stable, tool that drastically improves the installation process of many, python-based, cli apps.
Pipx all but eliminates the concerns mentioned here: [whats-the-advantage-of-this-mode-of-installation-instead-of-regular-pip-inside-a-virtualenv](https://github.com/aws/aws-elastic-beanstalk-cli-setup#51-for-the-experienced-python-developer-whats-the-advantage-of-this-mode-of-installation-instead-of-regular-pip-inside-a-virtualenv)

**Comment by dustinbolton** [comment]
@yolabingo Thank you for sharing this. I spent hours trying to get things to work using pip and virtualenv. The install instructions failed repeatedly on my new Mac. pipx got everything working for me instantly.

**Comment by bradwbradw** [comment]
I installed using pipx, and then when I tried out `eb` i got:

```
 $ eb create my-env       
Traceback (most recent call last):
  File "/Users/brad/.local/bin/eb", line 7, in <module>
    from ebcli.core.ebcore import main
  File "/Users/brad/Library/Application Support/pipx/venvs/awsebcli/lib/python3.12/site-packages/ebcli/core/ebcore.py", line 16, in <module>
    from cement.core import foundation, handler, hook
  File "/Users/brad/Library/Application Support/pipx/venvs/awsebcli/lib/python3.12/site-packages/cement/core/foundation.py", line 11, in <module>
    from ..core import output, extension, arg, controller, meta, cache, mail
  File "/Users/brad/Library/Application Support/pipx/venvs/awsebcli/lib/python3.12/site-packages/cement/core/extension.py", line 8, in <module>
    from imp import reload  # pragma: no cover
    ^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'imp'
```

(edit) i see now it is an `eb` issue after all:  https://github.com/aws/aws-elastic-beanstalk-cli-setup/issues/153

**Comment by yolabingo** [comment]
@bradwbradw 
you can tell pipx to use an older python version by specifying another python executable on your path, for example 
`pipx install --python python3.11 awsebcli`
