### ISSUE TITLE
Syntax Error when running any command

### ISSUE THREAD

**Issue by yahya-uddin** [aws/aws-elastic-beanstalk-cli-setup#152]
**1. Please specify the following:**
 - OS: OSX ___
 - Shell: zsh ____

**2. Description**
After installing the CLI, as described in the docs I get the following error when I run "any" eb command:

```
Traceback (most recent call last):
  File "/Users/####/.ebcli-virtual-env/executables/eb", line 41, in <module>
    execfile(activate_this, dict(__file__=activate_this))
  File "/Users/####/.ebcli-virtual-env/bin/activate_this.py", line 18
    raise AssertionError(msg) from exc
                                 ^
SyntaxError: invalid syntax
```

**Comment by eremite** [comment]
I was able to work around this on Amazon Linux by forcing `eb` to use python 3 by opening `~/.ebcli-virtual-env/executables/eb` and changing the first line from this:

```
#!/usr/bin/env python
```

to this:
```
#!/usr/bin/env python3
```

**Comment by iosmonbekov** [comment]
@eremite Thanks it helped

**Comment by bolti95** [comment]
@eremite  thanks this saved me!

**Comment by cBevilaqua** [comment]
saved me on MAC OS 10.15.
