### ISSUE TITLE
Install fails on x64 Windows 10:  `ModuleNotFoundError: No module named 'virtualenv' Exiting due to failure`

### ISSUE THREAD

**Issue by phillhocking** [aws/aws-elastic-beanstalk-cli-setup#19]
I recently (as of this writing - 5/15/2019) attempted to install eb-cli through the instructions located here: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3-install.html?icmpid=docs_elasticbeanstalk_console#eb-cli3-install.scripts.windows

This installation errored out due to some kind of issue with a module that was installed or called incorrectly from what I can gather.

I discovered that another user had this same issue today via StackOverflow: https://stackoverflow.com/questions/56153387/modulenotfounderror-no-module-named-virtualenv-exiting-due-to-failure-even-a

Please find the output from the command below:

PS C:\Users\phillip.hocking> .\aws-elastic-beanstalk-cli-setup\scripts\bundled_installer 

==============================================
I. Installing Python
==============================================

**************************************************
1. Looking for existing Python 3.7.3 installation.
**************************************************

*************************************
2. Downloading x64 version of Python.
*************************************

***********************************************
3. Installing Python. Do not close this window.
***********************************************
Installing Python. Do not close this window.
Installation completed successfully.

*******************************************
4. Updating Environment PATH of this shell.
*******************************************

************************
5. Installing virtualenv
************************
Collecting virtualenv
  Downloading https://files.pythonhosted.org/packages/ca/ee/8375c01412abe6ff462ec80970e6bb1c4308724d4366d7519627c98691ab/virtualenv-16.6.0-py2.py3-none-any.whl (2.0MB)
    100% |████████████████████████████████| 2.0MB 1.8MB/s
Installing collected packages: virtualenv
Successfully installed virtualenv-16.6.0
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

==============================================
II. Creating self-contained EBCLI installation
==============================================
Installing the EBCLI in C:\Users\phillip.hocking\.ebcli-virtual-env

******************************************
1. Creating exclusive virtualenv for EBCLI
******************************************
Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\phillip.hocking\aws-elastic-beanstalk-cli-setup\scripts\virtualenv\bin\virtualenv.exe\__main__.py", line 5, in <module>
ModuleNotFoundError: No module named 'virtualenv'
Exiting due to failure`

**Comment by rahulrajaram** [comment]
Hi @phillhocking , 

Thanks for reaching out. This appears to be a bug in `virtualenv` on some Windows machines. Until we can fix this bug, you can get around it by doing:

1. `pip uninstall -y virtualenv`
2. `pip install virtualenv`
3. `python .\aws-elastic-beanstalk-cli-setup\scripts\ebcli_installer.py`

Let me know if this doesn't work.

**Comment by Diceps** [comment]
Make sure you run `pip install virtualenv` as administrator or `sudo` so that python won't install the packages to `/site-packages` which `virtualenv` won't get recognized in PATH. 

Only helped me by installing `virtualenv `by running cmd as administrator which installs the packages in `/dist-packages`. Same for linux with `sudo`.

**Comment by LahaLuhem** [comment]
> Hi @phillhocking ,
> 
> Thanks for reaching out. This appears to be a bug in how `virtualenv` is installed through `pip install --target` on some Windows machines. Until we fix this bug, you can get around it by doing:
> 
> 1. `pip uninstall -y virtualenv`
> 2. `pip install virtualenv`
> 3. `python .\aws-elastic-beanstalk-cli-setup\scripts\ebcli_installer.py`
> 
> Let me know if this doesn't work.

I still need to use the --target flag though.

**Comment by kaynetpc** [comment]
C:\Python311\python.exe: can't open file 'C:\\Users\\kayode\\.aws-elastic-beanstalk-cli-setupscriptsebcli_installer.py': [Errno 2] No such file or directory
