### ISSUE TITLE
How to uninstall aws eb cli?

### ISSUE THREAD

**Issue by ASchwad** [aws/aws-elastic-beanstalk-cli-setup#56]
Hey, **how do I uninstall this package?** my installation has failed and i would like to get back to a clean state. 
can I just delete this directory? `/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ebcli`

if i run "eb" i get the following error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/eb", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'blessed>=1.9.5' distribution was not found and is required by awsebcli
```

basically the script failed to install these dependencies:
```
awsebcli 3.15.3 requires docker-compose<1.24.0,>=1.23.2, which is not installed.
awsebcli 3.15.3 requires requests<2.21,>=2.20.1, which is not installed.
awsebcli 3.15.3 requires semantic_version==2.5.0, which is not installed.
awsebcli 3.15.3 has requirement PyYAML<=3.13,>=3.10, but you'll have pyyaml 5.1.2 which is incompatible.
awsebcli 3.15.3 has requirement six<1.12.0,>=1.11.0, but you'll have six 1.12.0 which is incompatible.
awsebcli 3.15.3 has requirement urllib3<1.25,>=1.24.1, but you'll have urllib3 1.25.6 which is incompatible.
```

**Comment by rahulrajaram** [comment]
Hi @ASchwad ,

sorry for the late response. This is a `pip` problem wherein the existence of multiple dependency conflicts is preventing a successful installation of the awsebcli.

Please know that is precisely the problem that the installation method prescribed by this repository is geared to solve. I recommend you give it a try.

**Comment by ben-burlingham** [comment]
For me, the `awsebcli` is not present in the `pip list` command from the $PATH.

Instead, it's on the `pip` executable(s) in this location (Windows, PowerShell format):

> $env:userprofile\.ebcli-virtual-env\Scripts\

I'm not a Pythonista, but it seems like deleting the `.ebcli-virtual-env` will remove it fully from the machine: https://stackoverflow.com/questions/11005457/how-do-i-remove-delete-a-virtualenv
