### ISSUE TITLE
Install Error - ModuleNotFoundError: No module named 'pyexpat'

### ISSUE THREAD

**Issue by aloisbarreras** [aws/aws-elastic-beanstalk-cli-setup#58]
**1. Please specify the following:**
 - MacOS 10.14.6
 - Zsh

- [X] **I have reviewed the troubleshooting tips described [here]() and they do not solve my problem**

**2. Description**
Error when running the `bundled_installer` command.

```
Traceback (most recent call last):
  File "/private/var/folders/h7/z_zhb_v92ts6zh9k2f52trv00000gn/T/python-build.20191015111544.68643/Python-3.7.2/Lib/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/private/var/folders/h7/z_zhb_v92ts6zh9k2f52trv00000gn/T/python-build.20191015111544.68643/Python-3.7.2/Lib/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/private/var/folders/h7/z_zhb_v92ts6zh9k2f52trv00000gn/T/python-build.20191015111544.68643/Python-3.7.2/Lib/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "/private/var/folders/h7/z_zhb_v92ts6zh9k2f52trv00000gn/T/python-build.20191015111544.68643/Python-3.7.2/Lib/ensurepip/__init__.py", line 204, in _main
    default_pip=args.default_pip,
  File "/private/var/folders/h7/z_zhb_v92ts6zh9k2f52trv00000gn/T/python-build.20191015111544.68643/Python-3.7.2/Lib/ensurepip/__init__.py", line 117, in _bootstrap
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/private/var/folders/h7/z_zhb_v92ts6zh9k2f52trv00000gn/T/python-build.20191015111544.68643/Python-3.7.2/Lib/ensurepip/__init__.py", line 27, in _run_pip
    import pip._internal
  File "/var/folders/h7/z_zhb_v92ts6zh9k2f52trv00000gn/T/tmpi007ibkr/pip-18.1-py2.py3-none-any.whl/pip/_internal/__init__.py", line 40, in <module>
  File "/var/folders/h7/z_zhb_v92ts6zh9k2f52trv00000gn/T/tmpi007ibkr/pip-18.1-py2.py3-none-any.whl/pip/_internal/cli/autocompletion.py", line 8, in <module>
  File "/var/folders/h7/z_zhb_v92ts6zh9k2f52trv00000gn/T/tmpi007ibkr/pip-18.1-py2.py3-none-any.whl/pip/_internal/cli/main_parser.py", line 8, in <module>
  File "/var/folders/h7/z_zhb_v92ts6zh9k2f52trv00000gn/T/tmpi007ibkr/pip-18.1-py2.py3-none-any.whl/pip/_internal/cli/cmdoptions.py", line 20, in <module>
  File "/var/folders/h7/z_zhb_v92ts6zh9k2f52trv00000gn/T/tmpi007ibkr/pip-18.1-py2.py3-none-any.whl/pip/_internal/utils/hashes.py", line 10, in <module>
  File "/var/folders/h7/z_zhb_v92ts6zh9k2f52trv00000gn/T/tmpi007ibkr/pip-18.1-py2.py3-none-any.whl/pip/_internal/utils/misc.py", line 21, in <module>
  File "/var/folders/h7/z_zhb_v92ts6zh9k2f52trv00000gn/T/tmpi007ibkr/pip-18.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py", line 35, in <module>
  File "/private/var/folders/h7/z_zhb_v92ts6zh9k2f52trv00000gn/T/python-build.20191015111544.68643/Python-3.7.2/Lib/plistlib.py", line 65, in <module>
    from xml.parsers.expat import ParserCreate
  File "/private/var/folders/h7/z_zhb_v92ts6zh9k2f52trv00000gn/T/python-build.20191015111544.68643/Python-3.7.2/Lib/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ModuleNotFoundError: No module named 'pyexpat'
make: *** [install] Error 1
```

Please let me know what further information you need from me to help debug this.

**Comment by rahulrajaram** [comment]
Hi @aloisbarreras , thanks for reaching out.

I actually don't  know how to fix this issue, but going by some information on related issues reported on GitHub, I am wondering whether an update to Xcode could solve the problem. The issue comes down to the right `expat` header files not being found even though Python itself ships with the necessary headers.
