### ISSUE TITLE
ModuleNotFoundError: No module named 'error'

### ISSUE THREAD

**Issue by DanielRivers** [aws/aws-elastic-beanstalk-cli-setup#69]
**1. Please specify the following:**
 - OS: [e.g. OS X, Ubuntu, Windows, etc.]: Windows
 - Shell (Bash, PowerShell, Zsh, etc.): Powershell

- [x] **I have reviewed the troubleshooting tips described [here]() and they do not solve my problem**

**2. Description**
I have installed ebcli, reviewed the steps and toubleshooting multiple times to no avail.  

When I run any eb command including eb --version I get errors

```
Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\DanDan\.ebcli-virtual-env\Scripts\eb.exe\__main__.py", line 4, in <module>
  File "c:\users\dandan\.ebcli-virtual-env\lib\site-packages\ebcli\core\ebcore.py", line 19, in <module>
    from ebcli.core import ebglobals, base, hooks
  File "c:\users\dandan\.ebcli-virtual-env\lib\site-packages\ebcli\core\hooks.py", line 20, in <module>
    from ebcli.core import fileoperations
  File "c:\users\dandan\.ebcli-virtual-env\lib\site-packages\ebcli\core\fileoperations.py", line 22, in <module>
    import yaml
  File "c:\users\dandan\.ebcli-virtual-env\lib\site-packages\yaml\__init__.py", line 2, in <module>
    from error import *
ModuleNotFoundError: No module named 'error'
```

I am not sure where to move forward with this.

**Comment by rahulrajaram** [comment]
@DanielRivers , thanks for reaching out. At first glance, it looks like it's an issue with how pyyaml is being installed. Can you try `pip install pyyaml` before running `eb --version` to see if it fixes the problem? Might give us a hint.

**Comment by DanielRivers** [comment]
Thanks for the prompt reply,  just tried and this was the output 

```
PS C:\development> pip install pyyaml
Requirement already satisfied: pyyaml in c:\users\dandan\appdata\roaming\python\python37\site-packages (5.2)
``` 

`eb -- version` still the same

**Comment by rahulrajaram** [comment]
@DanielRivers ,

Sorry for the delay in responding to you. Going by the text following `pip install pyyaml`, it seems that you have multiple `pip`s:

- one under `c:\program files\python37\`
- one under `c:\users\dandan\appdata\roaming\python\python37\`

So when you attempted to install `pyyaml` it did so using the `pip` in `c:\users\dandan\appdata\roaming\python\python37\`. Can you try using the `pip` in `c:\program files\python37\` to uninstall `pyyaml` and then to reinstall it?
