### ISSUE TITLE
ModuleNotFoundError: No module named 'virtualenv'

### ISSUE THREAD

**Issue by bennyn** [aws/aws-elastic-beanstalk-cli-setup#75]
**1. Please specify the following:**

 - OS: Windows 10
 - Shell (Bash, PowerShell, Zsh, etc.): cmd

**2. Description**

I executed the following 2 commands (without having Python 3.7.3 installed) in my **Command Prompt** on **Windows 10**:

```
git clone https://github.com/aws/aws-elastic-beanstalk-cli-setup.git
./aws-elastic-beanstalk-cli-setup/scripts/bundled_installer
```

After doing that I received the following error:

```
==============================================
II. Creating self-contained EBCLI installation
==============================================
Installing the EBCLI in C:\Users\bn\.ebcli-virtual-env

******************************************
1. Creating exclusive virtualenv for EBCLI
******************************************
Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\dev\env\aws-elastic-beanstalk-cli-setup\scripts\virtualenv\bin\virtualenv.exe\__main__.py", line 5, in <module>
ModuleNotFoundError: No module named 'virtualenv'
Exiting due to failure
```

**Screenshot**

![image](https://user-images.githubusercontent.com/469989/77558716-8fe04200-6ebb-11ea-8be7-c101b9bd5cfa.png)

**Comment by rahulrajaram** [comment]
@bennyn , thanks for reaching out. Unfortunately, this is a long-standing issue. Please find the current workaround [here](https://github.com/aws/aws-elastic-beanstalk-cli-setup/issues/19#issuecomment-492939544).

**Comment by minkbear** [comment]
@rahulrajaram Solution is work. Thank you.
