### ISSUE TITLE
`eb appversion` gives ERROR: ModuleNotFoundError - No module named '_curses'

### ISSUE THREAD

**Issue by edlins** [aws/aws-elastic-beanstalk-cli-setup#94]
**1. Please specify the following:**
 - OS: [e.g. OS X, Ubuntu, Windows, etc.]: Amazon Linux 2
 - Shell (Bash, PowerShell, Zsh, etc.): Bash

- [x] **I have reviewed the troubleshooting tips described [here]() and they do not solve my problem**

**2. Description**
```
$ eb appversion
ERROR: ModuleNotFoundError - No module named '_curses'
$ which python
~/.pyenv/versions/3.7.2/bin/python
$ python
Python 3.7.2 (default, Jul  9 2020, 22:58:11)
[GCC 7.3.1 20180712 (Red Hat 7.3.1-6)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import curses
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/.pyenv/versions/3.7.2/lib/python3.7/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
>>> quit()
$ /bin/python
Python 2.7.16 (default, Dec 12 2019, 23:58:22)
[GCC 7.3.1 20180712 (Red Hat 7.3.1-6)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import curses
>>> quit()
$ yum list installed|grep curses
ncurses.x86_64                        6.0-8.20170212.amzn2.1.3       installed
ncurses-base.noarch                   6.0-8.20170212.amzn2.1.3       installed
ncurses-c++-libs.x86_64               6.0-8.20170212.amzn2.1.3       @amzn2-core
ncurses-devel.x86_64                  6.0-8.20170212.amzn2.1.3       @amzn2-core
ncurses-libs.x86_64                   6.0-8.20170212.amzn2.1.3       installed
```

I have performed the Troubleshooting steps for Amazon Linux and re-run the `bundled_installer` which generated the attached output.  [inst.txt](https://github.com/aws/aws-elastic-beanstalk-cli-setup/files/5170627/inst.txt)

I am unfamiliar with python virtual environments but it appears the `.pyenv/versions/3.7.2/bin/python` is not built with `ncurses` support.

**Comment by agusavior** [comment]
I'm having this problem with the command eb health
